### PR TITLE
Didn't add anything just fixed the gifs with a cool class, and cleaned up the code.

### PR DESCRIPTION
**Pull request by andrewccard**

### CODE REVIEW

**Comment by roanmorgan53** [comment]
bro deleted my exitButton 😢

**Comment by andrewccard** [comment]
> bro deleted my exitButton 😢

I just made the actual x button work instead

**Comment by roanmorgan53** [comment]
my exit button had rizz

**Comment by andrewccard** [comment]
> my exit button had rizz

well then copy paste it back from the old commit

**Pull request merged**
